
server:

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:teste
    username: sa
    password: ""

  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

springdoc:
  swagger-ui:
    enabled: true
mybatis:
  mapper-locations: classpath:/mapper/*.xml
